awshome/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.staticfiles.urls import static

from . import settings_common, settings_dev



urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
]

urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name="top"),
    path('contact/', views.InquiryView.as_view(), name='contact'),

    path('works/', views.works, name='works'),
    path('works/<int:num>', views.works, name='works'),
    path('works/<str:url>', views.works_detail, name='works_detail'),
    path('about/', views.about, name='about'),

    path('blog/', views.blog, name='blog'),
    path('blog/<int:num>', views.blog, name='blog'),
    path('blog/<str:url>', views.blog_detail, name='blog_detail'),

]

home/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to='images/')
    url = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Movie(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    url = models.CharField(max_length=200)

    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
# Create your models here.

home/forms.py
from django import forms
from django.core.mail import EmailMessage


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    inquiry = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea(attrs={'cols': 50, 'rows': 10}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        inquiry = self.cleaned_data['inquiry']

        message = EmailMessage(subject=name + "からの問い合わせ",
                               body=inquiry,
                               from_email=email,
                               to=["0927ryota.Sgmail.com"],
                               cc=[email])
        message.send()

home/views.py
from django.shortcuts import render
from django.views import generic
from . import forms
import logging
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Post, Movie
from django.core.paginator import Paginator


logger = logging.getLogger(__name__)

# Create your views here.



def index(request, num=1):
    date = Movie.objects.all().order_by('published_date').reverse()
    date2 = Post.objects.all().order_by('published_date').reverse()
    page = Paginator(date, 5)
    page2 = Paginator(date2, 4)
    params = {
        'title': 'Top',
        'msg': 'toppagedesu.',
        'date': page.get_page(num),
        'date2': page2.get_page(num)

    }
    return render(request, 'home/top.html', params)


class InquiryView(generic.FormView):
    template_name = "home/contact.html"
    form_class = forms.InquiryForm
    success_url = reverse_lazy('home:contact')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,'おくったよ')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)





def works(request, num=1):
    date = Movie.objects.all().order_by('published_date').reverse()
    page = Paginator(date, 3)
    params = {
        'title': 'Music',
        'msg': 'workpagedesu.',
        'date': page.get_page(num)
    }
    return render(request, 'home/works.html', params)


def works_detail(request, url):
    date = Movie.objects.filter(url=url)
    params = {
        'title': 'Music',
        'msg': 'workpagedesu.',
        'date': date
    }
    return render(request, 'home/works_detail.html', params)


def about(request):
    params = {
        'title': 'About',
        'msg': 'aboutpagedesu.',
    }
    return render(request, 'home/index.html', params)


def blog(request, num=1):
    date = Post.objects.all().order_by('published_date').reverse()
    page = Paginator(date, 3)
    params = {
        'title': 'Blog',
        'msg': 'blogpagedesu.',
        'date': page.get_page(num)
    }
    return render(request, 'home/blog.html', params)


def blog_detail(request, url):
    date = Post.objects.filter(url=url)
    params = {
        'title': 'Blog',
        'msg': 'blogpagedesu.',
        'date': date
    }
    return render(request, 'home/blog_detail.html', params)

home/templates/home/blog.html
{% extends 'home/index.html' %}
{% block content %}
    <table class="table">
    {% for item in date %}
        <div class="post" style=" padding: 50px 0px;" id="post">
            <p class="date" id="date">
                {{ item.published_date |date:"Y.m.d"}}
            </p>
            <h2><a href="{% url 'home:blog' %}{{ item.url }}" id="link" class="text-decoration-none">{{ item.title }}</a></h2>
            <img src="{{ item.image.url }}">
            <p>{{ item.text|linebreaksbr }}</p>
            
            
            
            
        </div>
    {% endfor %}

    <ul class="pagination">
        <li class="page-item ">
            <a class="page-link" >
            {{ date.number}}/{{ date.paginator.num_pages}}</a>
        </li>
        {% if date.has_previous %}
        <li class="page-item a">
            <a class="page-link" href="{% url 'home:blog' %}">
                &laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'home:blog' %}{{date.previous_page_number}}">
                {{date.previous_page_number}}</a>
        </li>
        {% else %}
        
        {% endif %}
        <li class="page-item now">
            <a class="page-link">
            {{ date.number}}</a>
        </li>
        {% if date.has_next %}
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'home:blog'  %}{{date.next_page_number}}">
                {{date.next_page_number}}</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'home:blog' %}{{date.paginator.num_pages}}">
                &raquo;</a>
        </li>
        {% else %}
        
        {% endif %}
    </ul>

       
    
    </table>

{% endblock %}

home/templates/home/blog_detail.html
{% extends 'home/index.html' %}
{% block content %}
    <table class="table">
    {% for item in date %}
        <div class="post" style=" padding: 50px 0px;" id="post">
            <p class="date" id="date">
                {{ item.published_date |date:"Y.m.d"}}
            </p>
            <h2 id="detail_title">{{ item.title }}</h2>
            <img src="{{ item.image.url }}" >
            <p id="detail_text">{{ item.text|linebreaksbr }}</p>
            
        </div>
    {% endfor %}

    
    <a id ="backlink" href="{{request.META.HTTP_REFERER}}">Back</a>

       
    
    </table>

{% endblock %}

home/templates/home/contact.html
{% extends 'home/index.html' %}

{% block content %}

<div class="page-header" style=" padding: 10px 0px;">
    <h1 id="title">contact</h1>
    <p>contactdesu</p>
</div>


<form  method="post">
     {% csrf_token %}
     {{ form.non_field_errors }}
     
     {% for field in form %}
       <div style=" padding: 20px 0px;">
         <label for="{{ field.id_for_label }}" id="tii">
           {{ field.label_tag }}
         </label>
         <div >
           {{ field }}
           {{ field.errors }}
         </div>
       </div>
     {% endfor %}
     <button  type="submit" class="btn btn-secondary ">送信</button> 
   </form>



{% endblock %}

home/templates/home/index.html
{% load static %}

<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">

    <link rel="stylesheet" type="text/css"
        href="{% static 'css/style.css' %}"/>

    <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        crossorigin="anonymous">
</head>

<body>
<div class="container-lg" style=" padding: 5% 5%; ">

    <div class="page-header">
    <h1 id="logo" style=" padding: 20px 0px;"><a href="{% url 'home:top' %}"class="text-decoration-none">Acerola</a></h1>

        <ul id="nav" class="ue" style=" padding: 20px 0px;">

            <li><a href="{% url 'home:about' %}">about</a></li>
            <li><a href="{% url 'home:works' %}">music</a></li>
            <li><a href="{% url 'home:blog' %}">blog</a></li>
            <li><a href="{% url 'home:contact' %}">contact</a></li>

        </ul>
    </div>



    <div class="page-header" style=" padding: 10px 0px;">
    <h1 id="title">{{title}}</h1>
    <p>{{msg}}</p>
    </div>
    <div class="contents">
        <div class="row">
            <div class="col-md-12">


    {% if messages %}
                <div class="container">
                    <div class="row">
                        <div class="my-div-style w-100">
                        <ul class="messages" style="list-style: none;">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                            </div>
                    </div>
                </div>
                {% endif %}

    {% block content %}{% endblock %}


            </div>
        </div>
    </div>

    <div class="page-footer ">


        <ul id="nav" class="sita" style=" padding: 20px 0px;">

            <li><a href="{% url 'home:about' %}">about</a></li>
            <li><a href="{% url 'home:works' %}">works</a></li>
            <li><a href="{% url 'home:blog' %}">blog</a></li>
            <li><a href="{% url 'home:contact' %}">contact</a></li>

        </ul>
    </div>


</div>



</body>
</html>

home/templates/home/top.html
{% extends 'home/index.html' %}
{% block content %}

<div id="mainVisual" style=" padding: 0% 0% 20%;">
    <img src="../../static/img/top.jpg" >
</div>



<div style=" padding: 0% 0% 20%;">

    <h1 id="title" class="toptext "><a href="{% url 'home:works' %}" class="text-decoration-none">Music</a></h1>
    <div class="container-fluid topmove" style=" padding: 10px 0px;">
    <ul id="top">
    {% for item in date %}
    <li id="top2">
    <div style=" padding: 20px 0px;">
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" style=" padding: 3px 5px;"
        src="{{ item.text}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    </div>

    <h2><a href="{% url 'home:works' %}{{ item.url }}" id="link" class="text-decoration-none" >{{ item.title }}</a></h2>
    </div>
    </li>
    {% endfor %}
    </ul>
    </div>


</div>

<div style=" padding: 0% 0% 20%;">

    <h1 id="title" class="toptext"><a href="{% url 'home:blog' %}"class="text-decoration-none">Blog</a></h1>
    <div class="container-fluid topblog" style=" padding: 10px 0px;" id="post">
    <ul id="top">
    {% for item in date2 %}
    <li id="top2">

        <div class="post" style=" padding: 30px 0px;">
            <div class="date" id="top_date">
            {{ item.published_date |date:"Y.m.d" }}
            </div>
            <a href="{% url 'home:blog' %}{{ item.url }}" id="link" class="text-decoration-none"><img src="{{ item.image.url }}" style=" padding: 0px 5px;"></a>

            <h2><a href="{% url 'home:blog' %}{{ item.url }}" id="link" class="text-decoration-none">{{ item.title }}</a></h2>


        </div>
        </li>
    {% endfor %}
    </ul>
    </div>
</div>









{% endblock %}

home/templates/home/works.html
{% extends 'home/index.html' %}
{% block content %}
{% for item in date %}
<table class="table" >
    <div class="container" style=" padding: 50px 0px;">
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item"
        src="{{ item.text}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    
    </div>
    <h2><a href="{% url 'home:works' %}{{ item.url }}" id="link" class="text-decoration-none">{{ item.title }}</a></h2>
    </div>
    
{% endfor %}

    

    <ul class="pagination">
        <li class="page-item ">
            <a class="page-link" >
            {{ date.number}}/{{ date.paginator.num_pages}}</a>
        </li>
        {% if date.has_previous %}
        <li class="page-item a">
            <a class="page-link" href="{% url 'home:works' %}">
                &laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'home:works' %}{{date.previous_page_number}}">
                {{date.previous_page_number}}</a>
        </li>
        {% else %}
        
        {% endif %}
        <li class="page-item now">
            <a class="page-link">
            {{ date.number}}</a>
        </li>
        {% if date.has_next %}
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'home:works'  %}{{date.next_page_number}}">
                {{date.next_page_number}}</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'home:works' %}{{date.paginator.num_pages}}">
                &raquo;</a>
        </li>
        {% else %}
        
        {% endif %}
    </ul>

       
    
</table>

{% endblock %}

home/templates/home/works_detail.html
{% extends 'home/index.html' %}
{% block content %}
{% for item in date %}
<table class="table" >
    <div class="container" style=" padding: 50px 0px;">
    <h2 id="detail_title">{{ item.title }}</h2>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item"
        src="{{ item.text}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    
    </div>
    
    </div>
    
{% endfor %}

<a id ="backlink" href="{{request.META.HTTP_REFERER}}">Back</a>


       
    
</table>

{% endblock %}